apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler

metadata:
  name: hello-nginx-vpa
  namespace: project1

spec:

  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-nginx

  updatePolicy:
    updateMode: Auto

  resourcePolicy:

    containerPolicies:

    - containerName: nginx

      minAllowed:
        cpu: 50m
        memory: 64Mi

      maxAllowed:
        cpu: 1000m
        memory: 1Gi